### PR TITLE
Added JSON serializer

### PR DESCRIPTION
**Pull request by TABeauchat**
Just added the json serializer to allow `from_json` to be called.

### CODE REVIEW

**Review by zeilhofe-xp360 — COMMENTED** [review]
Should we include tests like `sobj.responds_to(:to_json)`?

**Review by jacobdaddario — COMMENTED** [review]
This seems fine if there's a need for it. It's always nice to be able to re-use some existing Rails functionality. Obviously we don't want tests that are redundant with Rails, but perhaps we could just drop two lines into `sObject` to indicate that the class responds to `as_json` and `from_json`.

**Comment by asedge** [comment]
@jacobdaddario @zeilhofe-xp360 Either of you want to push up those specs & add a `CHANGELOG` entry? I'm happy to approve/merge afterwards.

**Comment by zeilhofe-xp360** [comment]
> @jacobdaddario @zeilhofe-xp360 Either of you want to push up those specs & add a `CHANGELOG` entry? I'm happy to approve/merge afterwards.

Added specs.

**Review by asedge — APPROVED** [review]
LGTM!

**Pull request merged**
