### PR TITLE
Feature/fix chaining methods v2

### PR DESCRIPTION
**Pull request by sbelknap-bf**
The general idea of this PR is that if I instantiate a query, such as
```
first_active_query = active_query.where("Text_Label = 'foo'")
```
any subsequent queries chaining off the initial query, should not update the initial query.
```
second_active_query = first_active_query.where("Checkbox_Label = true")
expect(second_active_query).not_to eq first_active_query
expect(second_active_query.to_s).not_to eq first_active_query.to_s
```
but should instead leave the initial query untouched, and generate a new query instance and return the result of the new query.
Without the changes in this PR, the two expectations above would fail.

The reason for this change, is currently this type of modifying behavior can have unexpected results, in cases such as
```
selected_tradelines = Af::OpportunityTradeline.where(is_selected_flag: true, opportunity_id: '00605000009ynJ6AAI')
# returns 3 tradelines
selected_tradelines.all.map(&:is_conditional_debt_flag)
=> [false, false, false] 
conditional_tradelines = selected_tradelines.where(is_conditional_debt_flag: true)
# returns the same 3 tradelines...
conditional_tradelines.all.map(&:is_conditional_debt_flag)
=> [false, false, false]
# this should return empty
# if we inspect the query
selected_tradelines.to_s
=> "SELECT ... FROM Opportunity_tradeline__c WHERE (Is_Selected_Flag__c = true) AND (Opportunity_Id__c = '00605000009ynJ6AAI') AND (Is_Conditional_Debt_Flag__c = true)"
# two things have happened here. 
# first, the initial selected_tradelines query object has had its query string updated to include the 'Is_Conditional_Debt_Flag__c' = true condition
# and second, the conditional_tradelines query is not returning the expected results
conditional_tradelines.to_s == selected_tradelines.to_s
=> true
# so the conditional_tradelines query has the correct query string...
# but because the query object already has values assigned to @records, those @records are being returned instead of the new query results
selected_tradelines.object_id == conditional_tradelines.object_id
=> true
# the two queries are the same object
```

To fix this, using any query methods on an existing query will now return a new instance of a query object, and leave the original untouched.

### CODE REVIEW

**Review by asedge — CHANGES_REQUESTED** [review]
Noticed that the cached records are being returned on the new `ActiveQuery` object. Please have a look at the discussion in Slack.

**Comment by spacechurro** [comment]
@sbelknap-bf what's the scoop w/ this PR?

**Comment by rferg** [comment]
Fixes #47

**Review by JeffLuckett — APPROVED** [review]

**Comment by JeffLuckett** [comment]
@rferg - what is the status of this?  Are you dev complete?  Can we get a run through QA on this?

**Comment by spacechurro** [comment]
@sbelknap-bf @rferg what's the latest here? do we just need to get some QA eyes on it?

**Comment by rferg** [comment]
> @sbelknap-bf @rferg what's the latest here? do we just need to get some QA eyes on it?

@spacechurro Yep.  CI passed and I did some quick spot checks.

**Comment by spacechurro** [comment]
> > @sbelknap-bf @rferg what's the latest here? do we just need to get some QA eyes on it?
> 
> 
> 
> @spacechurro Yep.  CI passed and I did some quick spot checks.

Cool. @sbelknap-bf what feature or card can we attach it to so that we can get some QA on it?

**Comment by sbelknap-bf** [comment]
> > > @sbelknap-bf @rferg what's the latest here? do we just need to get some QA eyes on it?
> > 
> > 
> > @spacechurro Yep.  CI passed and I did some quick spot checks.
> 
> Cool. @sbelknap-bf what feature or card can we attach it to so that we can get some QA on it?

@rferg is there a trello card for the feature that originally identified the bug?

**Review by asedge — APPROVED** [review]
This looks solid to me. Nice work guys!

**Pull request merged**
